### ISSUE TITLE
"Typing" preview has a text break

### ISSUE THREAD

**Issue by Roawrenzo** [iFallUpHill/facebook-messenger-irc-flat-theme#1]
When people are typing the "is typing" symbol has a text break.
![2016-08-21 00_23_21-messenger](https://cloud.githubusercontent.com/assets/21152869/17835912/977430da-6735-11e6-8a41-2cc7240e7e3e.png)

-Using Chrome Version 52.0.2743.116 m (64-bit)

**Comment by iFallUpHill** [comment]
Fixed in https://github.com/iFallUpHill/facebook-messenger-irc-flat-theme/commit/d33613d694ef01c5f37004d0e3f0740dfda3dc77
