### ISSUE TITLE
Please man names hideable again

### ISSUE THREAD

**Issue by SinZer0** [iFallUpHill/facebook-messenger-irc-flat-theme#4]
I liked the old mode way more; I know dumb people want names to show, but please add back in the option for the rest of us who really like the IRC feel.

In the meantime I am just using an old version. Love the extension.

**Comment by iFallUpHill** [comment]
@SinZer0 how would you feel about Ctrl/Cmd + Click to activate it as a more secret user mode? One of the things that I heard a lot was that people didn't like that they didn't know who they were talking to, but I definitely think having both options would be nice. 

Sorry for the sudden change by the way!

**Comment by SinZer0** [comment]
@iFallUpHill That sounds fine, as long as people know how to do it! 

It's all good, I have been using it for over a year; instantly noticed something was up this morning. Just glad you are actually active; sign of a good developer!

**Comment by iFallUpHill** [comment]
@SinZer0 Yeah for sure, I'm really glad that you're giving me this feedback. I know the change I made was pretty big, but I did it mainly because the feedback that I'd get in person a lot was that it was really hard to tell who was who for some people. I'll try and get something out asap! :)

**Comment by iFallUpHill** [comment]
@SinZer0 I've released v1.4 which contains this new functionality. Please let me know what you think about it!

**Comment by SinZer0** [comment]
It's perfect! Thank you! Left a review and everything (Can't believe I never did that before)
